name: ubuntu

on:
  push:
    branches:
    - main
    - dev

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        dc: [ ldc-latest, dmd-latest ]

    name: "${{matrix.os}}:${{matrix.dc}}"

    steps:

    - name: 'Setup Compiler'
      uses: dlang-community/setup-dlang@v2

    - name: 'Checkout'
      uses: actions/checkout@v7.0.1

    - name: 'Build & Test'
      run: |
        # Build the project, without unittests
        dub build -b release --compiler=$DC
        # Build and run tests
        dub test -b unittest-cov --compiler=$DC

    - name: 'Upload coverage reports to Codecov'
      if: matrix.dc == 'ldc-latest'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        # Upload code coverage
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov

